development:
  adapter: postgresql
  encoding: unicode
  database: ft-020121-movies
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: production